### ISSUE TITLE
[orchesrator] leadership lock when service not ready ( unsynch)

### ISSUE THREAD

**Issue by branciard** [luguslabs/archipel#105]
during some tests, I reset the volume of kusama, and so it starts to synch again to 0.
as the leadership check is before check of synch. The node stay in passive mode ( as expected)  and no others node take the leadership. maybe we must not propagate metrics transactions in this case to allow others to take leadership.
logs order :
```
Current node is leader...
Checking is service is ready to start...
```

**Comment by vladostp** [comment]
Fixed in #145
