### ISSUE TITLE
Cannot change zip config ( node key file ) without remove docker volume

### ISSUE THREAD

**Issue by branciard** [luguslabs/archipel#113]
As there is return if the file is already present : https://github.com/luguslabs/archipel/blob/719335371d85dcdde5594d7bcba04c36a543d6e0/orchestrator/src/polkadot.js#L346

```
      // Check if node key file is already present
      if (fs.existsSync(`/service/keys/${config.polkadotNodeKeyFile}`)) {
        console.log(`File ${config.polkadotNodeKeyFile} is already in /service/key directory...`);
        return;
      }
```
The new node file key config is not taken and `reserve-only` on validator will not be able to connect to any centry nodes peers.
The solution was to remove the service volume manually. 
If we keep this check and return may be add a env varibale to `--overwrite-node-key-file` when we really want to change the config without removing docker volumes.

( I see this problem when i change  from IP to DNS config during testing )

**Comment by vladostp** [comment]
Fixed in #121.
