### ISSUE TITLE
add wiregard VPN between polkadot sentry nodes and validator node

### ISSUE THREAD

**Issue by branciard** [luguslabs/archipel#26]
more details here https://wiki.polkadot.network/docs/en/maintain-guides-how-to-setup-sentry-node

**Comment by vladostp** [comment]
In #40 we added the ability to run Archipel with WireGuard VPN. 
The example how to launch Archipel with VPN is available here: https://github.com/luguslabs/archipel/tree/dev#archipel-with-wireguard-vpn
The Polkadot service can also be launched in VPN by setting `POLKADOT_LAUNCH_IN_VPN` variable to `true`.
